# Generated by Django 5.2.4 on 2025-08-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='is_available',
        ),
    ]
