# Generated by Django 5.2.4 on 2025-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_available_car_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('is_available', 'Available'), ('pending', 'Pending Sale'), ('sold', 'Sold'), ('maintenance', 'In Maintenance')], default='is_available', max_length=20),
        ),
    ]
