# Generated by Django 5.2.4 on 2025-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter full URL to the car image', max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
