# Generated by Django 5.2.4 on 2025-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_car_image_car_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
