# Generated by Django 5.2.4 on 2025-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
