# Generated by Django 5.2.4 on 2025-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=50),
        ),
    ]
