# Generated by Django 5.2.4 on 2025-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15),
        ),
    ]
