# Generated by Django 5.2.4 on 2025-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_car_make_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=25),
        ),
    ]
