# Generated by Django 5.2.4 on 2025-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_car_make_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(default=None),
        ),
    ]
