# Generated by Django 5.2.4 on 2025-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_testdrive_email_testdrive_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='phone',
        ),
        migrations.AddField(
            model_name='testdrive',
            name='customer_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='customer_phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
