# Generated by Django 5.2.4 on 2025-08-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_email_testdrive_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
