# Generated by Django 5.2.4 on 2025-12-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_customer_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
